CREATE TABLE IF NOT EXISTS localizacao(
    id BIGSERIAL PRIMARY KEY,
    endereco VARCHAR(255) NOT NULL,
    andar VARCHAR(50) NOT NULL,
    descricao VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);